// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StorageRequest struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (m *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(m, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MobileNumber         string   `protobuf:"bytes,4,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Item) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

type StorageReply struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	Processed            []string `protobuf:"bytes,2,rep,name=processed,proto3" json:"processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageReply) Reset()         { *m = StorageReply{} }
func (m *StorageReply) String() string { return proto.CompactTextString(m) }
func (*StorageReply) ProtoMessage()    {}
func (*StorageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *StorageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageReply.Unmarshal(m, b)
}
func (m *StorageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageReply.Marshal(b, m, deterministic)
}
func (m *StorageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageReply.Merge(m, src)
}
func (m *StorageReply) XXX_Size() int {
	return xxx_messageInfo_StorageReply.Size(m)
}
func (m *StorageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageReply.DiscardUnknown(m)
}

var xxx_messageInfo_StorageReply proto.InternalMessageInfo

func (m *StorageReply) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *StorageReply) GetProcessed() []string {
	if m != nil {
		return m.Processed
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageRequest)(nil), "storage.StorageRequest")
	proto.RegisterType((*Item)(nil), "storage.Item")
	proto.RegisterType((*StorageReply)(nil), "storage.StorageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Save(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageReply, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Save(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageReply, error) {
	out := new(StorageReply)
	err := c.cc.Invoke(ctx, "/storage.Storage/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Save(context.Context, *StorageRequest) (*StorageReply, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Save(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _Storage_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x6d, 0xda, 0xb2, 0x63, 0xb7, 0x87, 0xc1, 0x8f, 0x20, 0x1e, 0x4a, 0x7a, 0xe9,
	0xa9, 0x87, 0x8a, 0xe0, 0x5d, 0x2f, 0x5e, 0x3c, 0xa4, 0x3f, 0x40, 0xb2, 0xee, 0x20, 0x81, 0xa4,
	0x89, 0x49, 0x2a, 0xf4, 0xdf, 0x8b, 0xc9, 0xba, 0x22, 0xde, 0xe6, 0x7d, 0x1e, 0x12, 0xe6, 0x1d,
	0x68, 0x63, 0x72, 0x41, 0xbd, 0xd3, 0xd6, 0x07, 0x97, 0x1c, 0xce, 0x87, 0x28, 0xee, 0x61, 0xb9,
	0x2f, 0xa3, 0xa4, 0x8f, 0x23, 0xc5, 0x84, 0x6b, 0x98, 0xea, 0x44, 0x36, 0xf2, 0x6a, 0x35, 0xd9,
	0x9c, 0xef, 0xda, 0xed, 0xcf, 0xcb, 0xe7, 0x44, 0x56, 0x16, 0x27, 0x08, 0xd8, 0x77, 0xc4, 0x25,
	0xd4, 0xba, 0xe7, 0xd5, 0xaa, 0xda, 0x34, 0xb2, 0xd6, 0x3d, 0x22, 0xb0, 0x83, 0xb2, 0xc4, 0xeb,
	0x4c, 0xf2, 0x8c, 0x17, 0x30, 0x25, 0xab, 0xb4, 0xe1, 0x93, 0x0c, 0x4b, 0xc0, 0x35, 0xb4, 0xd6,
	0x75, 0xda, 0xd0, 0xeb, 0xe1, 0x68, 0x3b, 0x0a, 0x9c, 0x65, 0xbb, 0x28, 0xf0, 0x25, 0x33, 0xf1,
	0x04, 0x8b, 0x71, 0x3b, 0x6f, 0x4e, 0x78, 0x05, 0x33, 0x0a, 0xc1, 0x85, 0xb2, 0x5c, 0x23, 0x87,
	0x84, 0xb7, 0xd0, 0xf8, 0xe0, 0xde, 0x28, 0x46, 0xea, 0x79, 0x9d, 0xd5, 0x2f, 0xd8, 0x3d, 0xc2,
	0x7c, 0xf8, 0x05, 0x1f, 0x80, 0xed, 0xd5, 0x27, 0xe1, 0xf5, 0xd8, 0xea, 0x6f, 0xfb, 0x9b, 0xcb,
	0xff, 0xc2, 0x9b, 0x93, 0x38, 0xeb, 0x66, 0xf9, 0x70, 0x77, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0x63, 0x22, 0xf3, 0x49, 0x01, 0x00, 0x00,
}
